# MCP Agent Configuration
# Configuration for Fed Job Advisor MCP agent server

server:
  name: "fed-job-advisor-general-purpose-agent"
  version: "1.0.0"
  description: "General-purpose MCP agent for Fed Job Advisor using local LLM"
  host: "localhost"
  port: 8080
  log_level: "INFO"

# Ollama configuration
ollama:
  url: "http://localhost:11434"
  model: "llama3.1:8b"
  fallback_model: "mistral:7b"
  temperature: 0.1
  max_tokens: 4096
  timeout: 300

# Agent behavior settings
agent:
  cost_per_token: 0.0  # Free local inference
  enable_context_caching: true
  max_context_window: 8192
  enable_async_processing: true

# Fed Job Advisor context
fed_job_advisor:
  frontend_url: "https://fedjobadvisor-frontend.onrender.com"
  backend_url: "https://fedjobadvisor-backend.onrender.com"
  database_type: "postgresql"
  deployment_platform: "render"
  target_launch: "Q1 2025"
  pricing_tiers:
    local: 29
    mobile: 49

# Performance monitoring
monitoring:
  enable_metrics: true
  metrics_port: 8081
  log_file: "logs/mcp_server.log"
  performance_tracking: true